config/routes.rb
Rails.application.routes.draw do

  scope module: :admin do
    resources :tags
    resources :users
    resources :documents do
      get 'image', on: :member
      resources :tags, except: :all do
        member do 
          post :tag
          post :untag
        end
      end
      resources :attachments #, shallow: true
    end
    resources :sites
    get 'profile', to: 'users#profile'
    patch 'update_profile', to: 'users#update_profile'
  end


  get  'login', to: 'login#log_in'
  post 'login', to: 'login#submit'
  get 'logout', to: 'login#log_out'


  scope module: :public do

    resources :articles , path: 'articulos'
    resources :recipes  , path: 'recetas'
    resources :resources, path: 'recursos' do
    # TODO:  get :download, on: :member
    end

    get :not_found,
      to: 'public#not_found',
      as: :not_found

    get '/:id', to: 'pages#show', as: :page

    root 'public#home'
  end

  # For details on the DSL available within this file,
  # see http://guides.rubyonrails.org/routing.html
end

app/models/site.rb
class Site < ApplicationRecord
  has_many :documents

  validates :code, :name, :description,
    presence: true
  validates :code, uniqueness: true

  def pages
    documents.where(kind: :page)
  end

  def articles
    documents.where(kind: :article)
  end

  def recipes
    documents.where(kind: :recipe)
  end

  def resources
    documents.where(kind: :resource)
  end

end

app/controllers/admin/sites_controller.rb
class Admin::SitesController < Admin::AdminController
  before_action :set_site, only: [:show, :edit, :update, :destroy]
  before_action :only_authorize_admin

  # GET /sites
  # GET /sites.json
  def index
    @sites = Site.all
  end

  # GET /sites/1
  # GET /sites/1.json
  def show
  end

  # GET /sites/new
  def new
    @site = Site.new
  end

  # GET /sites/1/edit
  def edit
  end

  # POST /sites
  # POST /sites.json
  def create
    @site = Site.new(site_params)

    respond_to do |format|
      if @site.save
        format.html { redirect_to @site, success: 'El sitio fue creado con éxito.' }
        format.json { render :show, status: :created, location: @site }
      else
        format.html { render :new }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sites/1
  # PATCH/PUT /sites/1.json
  def update
    respond_to do |format|
      if @site.update(site_params)
        format.html { redirect_to @site, success: 'El sitio fue actualizado con éxito.' }
        format.json { render :show, status: :ok, location: @site }
      else
        format.html { render :edit }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sites/1
  # DELETE /sites/1.json
  def destroy
    @site.destroy
    respond_to do |format|
      format.html { redirect_to sites_url, success: 'El sitio fue eliminado con éxito.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_site
      @site = Site.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def site_params
      params.require(:site).permit(:code, :name, :description)
    end
end

app/views/admin/sites/_form.html.erb
<%= form_for(site) do |f| %>
  <% if site.errors.any? %>
    <article class="alert alert-danger">
      <%= site.errors.count %>
      error(es) no permiten guardar este sitio web:
     
      <ul>
        <% site.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </article>
  <% end %>

  <fieldset class="form-group">
    <%= f.label :code, 'Código' %>
    <%= f.text_field :code,
        class: 'form-control' %>
  </fieldset>

  <fieldset class="form-group">
    <%= f.label :name, 'Nombre' %>
    <%= f.text_field :name,
        class: 'form-control' %>
  </fieldset>

  <fieldset class="form-group">
    <%= f.label :description,
        'Descripción' %>
    <%= f.text_field :description,
        class: 'form-control' %>
  </fieldset>

  <div class="actions">
    <%= f.submit 'Guardar',
        class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/admin/sites/edit.html.erb
<h1>Sitio Web</h1>

<section class="card">
  <section class="card-block">
    <%= render 'form', site: @site %>
  </section>
</section>

<%= link_to 'Ver', @site %> |
<%= link_to 'Volver', sites_path %>

app/views/admin/sites/index.html.erb
<h1>Sitios Web</h1>

<section class="card">
  <section class="card-block">

<table class="table">
  <thead>
    <tr>
      <th>Código</th>
      <th>Nombre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sites.each do |site| %>
      <tr>
        <td><%= site.code %></td>
        <td><%= site.name %></td>
        <td><%= link_to 'Ver', site %></td>
        <td><%= link_to 'Editar', edit_site_path(site) %></td>
        <td><%= link_to 'Eliminar', site, method: :delete, data: { confirm: '¿Está seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo sitio web', new_site_path, class: 'btn btn-primary' %>

  </section>
</section>

app/views/admin/sites/new.html.erb
<h1>Nuevo sitio</h1>

<section class="card">
  <section class="card-block">
    <%= render 'form', site: @site %>
  </section>
</section>

<%= link_to 'Volver', sites_path %>

app/views/admin/sites/show.html.erb
<h1>
  Sitio Web
  <small class="link">
    <%= link_to 'editar',
      edit_site_path(@site) %>
  </small>
</h1>

<section class="card">
<section class="card-block">

<p>
  <strong>Código:</strong>
  <%= @site.code %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @site.name %>
</p>

<p>
  <strong>Descripción:</strong>
  <%= @site.description %>
</p>

</section>
</section>

<%= link_to 'Volver', sites_path %>